"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Empleado_js_1 = require("../Empleado/Empleado.js");
var Fabrica_js_1 = require("../Fabrica/Fabrica.js");
var empleado1 = new Empleado_js_1.Empleado(1000, 10000, "Agustin", "Rivola", 42432112, "M");
var empleado3 = new Empleado_js_1.Empleado(1002, 10000, "Santiago", "Aguado", 43221102, "M");
var empleado2 = new Empleado_js_1.Empleado(1001, 12000, "Paula", "Sosa", 41402212, "F");
var empleado4 = new Empleado_js_1.Empleado(1003, 10000, "Siles", "Jazmin", 41029292, "F");
console.log(empleado1.Hablar("Español"));
console.log("\n" + empleado1.ToString());
console.log("\n\n\n------------Pruebo clase fabrica----------\n\n\n");
var unaFabrica = new Fabrica_js_1.Fabrica("Autos");
unaFabrica.AgregarEmpleado(empleado1);
unaFabrica.AgregarEmpleado(empleado2);
unaFabrica.AgregarEmpleado(empleado3);
unaFabrica.AgregarEmpleado(empleado4);
console.log("\n" + "\n" + unaFabrica.ToString());
unaFabrica.EliminarEmpleado(empleado2);
unaFabrica.EliminarEmpleado(empleado3);
console.log("\n" + "\n" + unaFabrica.ToString());
